### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hasmal95** [nafalabi/albn-fishing-bot#3]
Hello mate! i want to know if i can run it with windows.... i am little noob xD thanks! :)

**Comment by hasmal95** [comment]
i run the code but i always i get this error and i don't know how to fix it xD

i run it with powershell (Admin)
and with cmd in the fishing folder...

C:\Windows\System32>npm install robotjs
npm warn deprecated npmlog@4.1.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm warn deprecated gauge@2.7.4: This package is no longer supported.
npm warn cleanup Failed to remove some directories [
npm warn cleanup [
npm warn cleanup 'C:\Windows\System32\node_modules\prebuild-install',
npm warn cleanup [Error: EPERM: operation not permitted, rmdir 'C:\Windows\System32\node_modules\prebuild-install\node_modules'] {
npm warn cleanup errno: -4048,
npm warn cleanup code: 'EPERM',
npm warn cleanup syscall: 'rmdir',
npm warn cleanup path: 'C:\Windows\System32\node_modules\prebuild-install\node_modules'
npm warn cleanup }
npm warn cleanup ]
npm warn cleanup ]
npm error code 1
npm error path C:\Windows\System32\node_modules\robotjs
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm error MSBUILD : error MSB1009: Project file does not exist.
npm error Switch: build\binding.sln
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.14.0 | win32 | x64
npm error gyp info find Python using Python version 3.12.4 found at "C:\Users\Matthaios\AppData\Local\Programs\Python\Python312\python.exe"
npm error gyp info find VS using VS2022 (17.10.35004.147) found at:
npm error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Users\Matthaios\AppData\Local\Programs\Python\Python312\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\Users\Matthaios\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\Windows\System32\node_modules\robotjs\build\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\Users\Matthaios\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\Users\Matthaios\AppData\Local\node-gyp\Cache\20.14.0\include\node\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\Users\Matthaios\AppData\Local\node-gyp\Cache\20.14.0',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\Users\Matthaios\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\Users\\Matthaios\\AppData\\Local\\node-gyp\\Cache\\20.14.0\\<(target_arch)\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=C:\Windows\System32\node_modules\robotjs',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'C:\Windows\System32\node_modules\robotjs\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'build\binding.sln',
npm error gyp info spawn args '/clp:Verbosity=minimal',
npm error gyp info spawn args '/nologo',
npm error gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe failed with exit code: 1
npm error gyp ERR! stack at ChildProcess. (C:\Users\Matthaios\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.22631
npm error gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Matthaios\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
npm error gyp ERR! cwd C:\Windows\System32\node_modules\robotjs
npm error gyp ERR! node -v v20.14.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: C:\Users\Matthaios\AppData\Local\npm-cache_logs\2024-06-14T16_42_32_722Z-debug-0.log

**Comment by nafalabi** [comment]
yes you can, this app can only run on windows

you need to install the dependencies first before using it\
you can follow the steps from [flora's page](https://github.com/FashionFlora/Albion-Online-Radar-QRadar), the installation process is the same\
additionally, you would also need to install the dependencies inside `vendor/photon-packet-parser` directory

once all set you can run by `node app.js`

**Comment by nafalabi** [comment]
tbh I don't know if this still works, I haven't played again for quite some time now. I'm not sure if the offsets and the event codes are still valid

**Comment by hasmal95** [comment]
oh ok mate, thanks :)

**Comment by hasmal95** [comment]
i do it like the video Tutorial from Flora's but i still take this error 

C:\Users\Matthaios\Downloads\albn-fishing-bot-main>node app.js
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'buffercursor'
Require stack:
- C:\Users\Matthaios\Downloads\albn-fishing-bot-main\vendor\photon-packet-parser\classes\PhotonPacket.js
- C:\Users\Matthaios\Downloads\albn-fishing-bot-main\vendor\photon-packet-parser\classes\PhotonPacketParser.js
- C:\Users\Matthaios\Downloads\albn-fishing-bot-main\vendor\photon-packet-parser\index.js
- C:\Users\Matthaios\Downloads\albn-fishing-bot-main\src\event-listener.js
- C:\Users\Matthaios\Downloads\albn-fishing-bot-main\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\Matthaios\Downloads\albn-fishing-bot-main\vendor\photon-packet-parser\classes\PhotonPacket.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Matthaios\\Downloads\\albn-fishing-bot-main\\vendor\\photon-packet-parser\\classes\\PhotonPacket.js',
    'C:\\Users\\Matthaios\\Downloads\\albn-fishing-bot-main\\vendor\\photon-packet-parser\\classes\\PhotonPacketParser.js',
    'C:\\Users\\Matthaios\\Downloads\\albn-fishing-bot-main\\vendor\\photon-packet-parser\\index.js',
    'C:\\Users\\Matthaios\\Downloads\\albn-fishing-bot-main\\src\\event-listener.js',
    'C:\\Users\\Matthaios\\Downloads\\albn-fishing-bot-main\\app.js'
  ]
}

Node.js v18.18.2

**Comment by hasmal95** [comment]
![gaga](https://github.com/nafalabi/albn-fishing-bot/assets/49456894/15de77a0-4151-42a3-9c0d-982d05e16f4d)

**Comment by hasmal95** [comment]
it work but it's makes random moves, it can not be fishing.... :( can you update it? or tell me how to manually fix it? Thanks you :)

**Comment by BorenVertex** [comment]
> it work but it's makes random moves, it can not be fishing.... :( can you update it? or tell me how to manually fix it? Thanks you :)

How have you fixed $ node app.js
process not found?

**Comment by nafalabi** [comment]
most likely because of invalid event codes or screen resolution problem

i'm not available to fix it, but let me give you some clues

1. you might want to use 1280x720 resolution. as this program was made to detect pixel changes so having different resolutions can be a problem. if you want to tweak it yourself, you can change the offsets in this file `src/dimensions.js`
2. the event codes may have changed. if this happens then the only thing you can do is to update with the correct ones. you can change it in this file `src/enums/FishingEvents.js`

since it's been a while, i'm pretty sure the event codes are already invalid

**Comment by nafalabi** [comment]
perhaps it was an invalid event codes issue or maybe a screen resolution issue. some clues you can try to fix it:

1. use 1280x720 resolution in your game. this program was made to detect pixel changes so having different resolutions can be a problem. and if you want to tweak it yourself, you can change the offsets in this file `src/dimensions.js`
2. the event codes may have changed. if this happens then the only thing you can do is to update with the correct ones. you can change it in this file `src/enums/FishingEvents.js`

since it's been a while, i'm pretty sure the event codes are already invalid

**Comment by BorenVertex** [comment]
> seems like invalid event codes or screen resolution problem. let me give you some clues
> 
> 1. use 1280x720 resolution. this program was made to detect pixel changes so having different resolutions can be a problem. if you want to tweak it yourself, you can change the offsets in this file `src/dimensions.js`
> 2. the event codes may have changed. if this happens then the only thing you can do is to update with the correct ones. you can change it in this file `src/enums/FishingEvents.js`
> 
> since it's been a while, i'm pretty sure the event codes are already invalid

and how can I get new event codes?

**Comment by nafalabi** [comment]
@BorenVertex I usually debug the events and do trial and error

**Comment by hasmal95** [comment]
so i change the event codes,
also i change the color
const getActionFromCoordinates = (pullPoint, restPoint) => {
    if ('#00ff00' !== getPixelColorAt(restPoint[0], restPoint[1])) {
        return 'rest'
    }

    if ('#4b8624' !== getPixelColorAt(pullPoint[0], pullPoint[1])) {
        return 'pull'

so now how i can change the resolution?

here is the dimension...

const robot = require('robotjs')

const getDimensions = (windowInstance) => {
    const dimensions = windowInstance.getDimensions()
    const winWidth = dimensions.right - dimensions.left
    const winHeight = dimensions.bottom - dimensions.top

    return {
        top: dimensions.top,
        bottom: dimensions.bottom,
        left: dimensions.left,
        right: dimensions.right,
        winHeight,
        winWidth,
    }
}

const getTargetCoordinates = (windowInstance) => {
    const {
        top,
        bottom,
        left,
        right,
        winHeight,
        winWidth,
    } = getDimensions(windowInstance)

    const yBuffer = 23;
    const x = left + (winWidth / 2)
    const y = top + (winHeight / 2) + yBuffer
    const center = [x, y - yBuffer]

    return {
        pullPoint: [x, y],
        restPoint: [x + 15, y],
        throwPoint: [x - 100, y - 65],
        fishBaitCoor: [center[0] + (center[0] * 0.375), center[1] + (center[1] * 0.15)],
        center,
    }
}

const getCurMouseCoor = () => {
    const coor = robot.getMousePos();
    return [coor.x, coor.y]
}

module.exports = {
    getTargetCoordinates,
    getCurMouseCoor,
}
